"""
LedgerPilot — Financial Statements (ledger-pilot copy)
"""

from chart_of_accounts import accounts_by_type


def income_statement(ledger, period_label: str) -> dict:
    revenues = {a["code"]: ledger.account_balance(a["code"]) for a in accounts_by_type("income")}
    expenses = {a["code"]: ledger.account_balance(a["code"]) for a in accounts_by_type("expense")}
    total_revenue = sum(revenues.values())
    total_expenses = sum(expenses.values())
    net_income = total_revenue - total_expenses
    return {
        "period": period_label,
        "revenues": revenues,
        "total_revenue": round(total_revenue, 2),
        "expenses": expenses,
        "total_expenses": round(total_expenses, 2),
        "net_income": round(net_income, 2),
    }


def balance_sheet(ledger, period_label: str) -> dict:
    assets = {a["code"]: ledger.account_balance(a["code"]) for a in accounts_by_type("asset")}
    liabilities = {a["code"]: ledger.account_balance(a["code"]) for a in accounts_by_type("liability")}
    equity = {a["code"]: ledger.account_balance(a["code"]) for a in accounts_by_type("equity")}
    total_assets = sum(assets.values())
    total_liabilities = sum(liabilities.values())
    total_equity = sum(equity.values())
    return {
        "period": period_label,
        "assets": assets,
        "total_assets": round(total_assets, 2),
        "liabilities": liabilities,
        "total_liabilities": round(total_liabilities, 2),
        "equity": equity,
        "total_equity": round(total_equity, 2),
        "balanced": round(total_assets, 2) == round(total_liabilities + total_equity, 2),
    }


def close_report(ledger, period_label: str, reconciliation_result: dict = None) -> str:
    bs = balance_sheet(ledger, period_label)
    pl = income_statement(ledger, period_label)
    report = f"""
LEDGERPILOT MONTHLY CLOSE REPORT
Period: {period_label}

--- INCOME STATEMENT ---
Total Revenue: ${pl['total_revenue']:,.2f}
Total Expenses: ${pl['total_expenses']:,.2f}
Net Income: ${pl['net_income']:,.2f}

--- BALANCE SHEET ---
Total Assets: ${bs['total_assets']:,.2f}
Total Liabilities: ${bs['total_liabilities']:,.2f}
Total Equity: ${bs['total_equity']:,.2f}
BALANCED: {bs['balanced']}

--- RECONCILIATION ---
{f'Matched: {len(reconciliation_result.get("matched", []))} transactions' if reconciliation_result else 'Not reconciled'}

Close Date: {period_label}
Generated by LedgerPilot
"""
    return report.strip()
